#!/bin/sh
sunxi-fel -v \
	spl prebuilt/sunxi-spl.bin \
	write 0x4a000000 prebuilt/u-boot-dtb.bin \
	write 0x42000000 rescue-kernel/boot/vmlinuz-4.4.11-ntc \
	write 0x43000000 rescue-kernel/usr/lib/linux-image-4.4.11-ntc/sun5i-r8-chip.dtb \
	write 0x43100000 boot-rescue.scr \
	write 0x43300000 rescue-rd.gz.img \
	exe 0x4a000000
