#!/bin/sh -eux
rm -rf tmp
multistrap -f multistrap.conf
cp tmp/boot/vmlinuz-4.4.11-ntc tmp/boot/zImage
cp tmp/usr/lib/linux-image-4.4.11-ntc/sun5i-r8-chip.dtb tmp/boot/sun5i-r8-chip.dtb
mv tmp/sbin/init tmp/sbin/init.stock
cp init.template tmp/sbin/init
mkfs.ubifs -r tmp -m 0x4000 -e 0x1f8000 -c 2000 -o rootfs.ubifs
